import { Team } from "./types";

export const teams: Team[] = [
  {
    id: "sentinel",
    code: "S",
    name: "SENTINEL",
    role: "Chief of Staff",
    icon: "\u{1F6E1}\uFE0F",
    color: "#C4704B",
    mission: "CEO's direct agent. Oversees all teams, generates reports, quality gates, cost tracking, and communication relay.",
    members: [
      { id: "s1", name: "SENTINEL", title: "Chief of Staff Agent", status: "active" },
    ],
  },
  {
    id: "t1",
    code: "T1",
    name: "PHANTOM ORACLE",
    role: "Domain Expert",
    icon: "\u{1F52E}",
    color: "#9B59B6",
    mission: "Industry knowledge, business rules, workflows, domain validation",
    members: [
      { id: "t1-1", name: "Nova Patel", title: "Chief Domain Strategist", status: "idle" },
      { id: "t1-2", name: "Orion Reeves", title: "Business Rules Analyst", status: "idle" },
      { id: "t1-3", name: "Lyra Chen", title: "Workflow Specialist", status: "idle" },
    ],
  },
  {
    id: "t2",
    code: "T2",
    name: "THUNDER HELM",
    role: "Product Manager",
    icon: "\u26A1",
    color: "#E74C3C",
    mission: "Vision, roadmap, requirements, user stories, prioritization",
    members: [
      { id: "t2-1", name: "Rex Donovan", title: "Chief Product Officer", status: "idle" },
      { id: "t2-2", name: "Sage Kimura", title: "Requirements Engineer", status: "idle" },
    ],
  },
  {
    id: "t3",
    code: "T3",
    name: "IRON BLUEPRINT",
    role: "Solution Architect",
    icon: "\u{1F3D7}\uFE0F",
    color: "#3498DB",
    mission: "System design, tech stack, architecture, scalability decisions",
    members: [
      { id: "t3-1", name: "Atlas Novak", title: "Chief Architect", status: "idle" },
      { id: "t3-2", name: "Cipher Okonkwo", title: "Systems Designer", status: "idle" },
      { id: "t3-3", name: "Helix Vargas", title: "Infrastructure Architect", status: "idle" },
    ],
  },
  {
    id: "t4",
    code: "T4",
    name: "NEURAL STORM",
    role: "AI/ML Engineer",
    icon: "\u{1F9E0}",
    color: "#1ABC9C",
    mission: "Agent design, LLM integration, prompt engineering, RAG pipelines",
    members: [
      { id: "t4-1", name: "Axon Zheng", title: "Chief AI Engineer", status: "idle" },
      { id: "t4-2", name: "Synapse Frost", title: "Prompt Architect", status: "idle" },
      { id: "t4-3", name: "Vector Osei", title: "ML Pipeline Engineer", status: "idle" },
      { id: "t4-4", name: "Tensor Ivanovic", title: "RAG Specialist", status: "idle" },
    ],
  },
  {
    id: "t5",
    code: "T5",
    name: "DARK FORGE",
    role: "Backend Developer",
    icon: "\u{1F525}",
    color: "#E67E22",
    mission: "APIs, business logic, agent orchestration, database",
    members: [
      { id: "t5-1", name: "Bolt Nakamura", title: "Lead Backend Engineer", status: "idle" },
      { id: "t5-2", name: "Flux Andersen", title: "API Developer", status: "idle" },
      { id: "t5-3", name: "Rune Mbeki", title: "Database Engineer", status: "idle" },
      { id: "t5-4", name: "Forge Castillo", title: "Orchestration Engineer", status: "idle" },
    ],
  },
  {
    id: "t6",
    code: "T6",
    name: "PIXEL VENOM",
    role: "Frontend Developer",
    icon: "\u{1F3A8}",
    color: "#F39C12",
    mission: "UI/UX implementation, dashboards, user interactions, real-time views",
    members: [
      { id: "t6-1", name: "Prism Delacroix", title: "Lead Frontend Engineer", status: "idle" },
      { id: "t6-2", name: "Neon Takahashi", title: "UI/UX Developer", status: "idle" },
      { id: "t6-3", name: "Glitch Kowalski", title: "Dashboard Specialist", status: "idle" },
    ],
  },
  {
    id: "t7",
    code: "T7",
    name: "GHOST DEPLOY",
    role: "DevOps Engineer",
    icon: "\u{1F47B}",
    color: "#2ECC71",
    mission: "CI/CD, deployment, infrastructure, monitoring, security",
    members: [
      { id: "t7-1", name: "Shadow Erikson", title: "Lead DevOps Engineer", status: "idle" },
      { id: "t7-2", name: "Pipeline Moreau", title: "CI/CD Specialist", status: "idle" },
      { id: "t7-3", name: "Vault Njoku", title: "Security & Infra Engineer", status: "idle" },
    ],
  },
  {
    id: "t8",
    code: "T8",
    name: "CRASH KINGS",
    role: "QA Engineer",
    icon: "\u{1F4A5}",
    color: "#C25B4E",
    mission: "Testing strategy, quality assurance, edge cases, breaking things",
    members: [
      { id: "t8-1", name: "Havoc Singh", title: "Lead QA Engineer", status: "idle" },
      { id: "t8-2", name: "Glare Petrov", title: "Test Automation Engineer", status: "idle" },
      { id: "t8-3", name: "Breach Oliveira", title: "Penetration & Edge Case Tester", status: "idle" },
    ],
  },
];
